version: "2"

run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
  
  disable:
    - errcheck
    - asciicheck
    - bodyclose
    - cyclop
    - dupl
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - grouper
    - importas
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

issues:
  exclude:
    # Exclude unused field warning
    - "field mu is unused"
